import React,{useEffect,useState} from 'react';
import {Text} from 'react-native';
import {Redirect} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {settingsApi} from '../src/api/settings.api';
import {useAuth} from '../src/auth/AuthProvider';
import {Card,ErrorState,Field,LoadingState,PrimaryButton,Screen,Title} from '../src/components/ui';
import {useTheme} from '../src/theme/ThemeProvider';

type SeoForm={site_name:string;site_url:string;default_title:string;default_description:string;default_og_image:string;google_site_verification:string;bing_site_verification:string;google_analytics_id:string};
type PageSeo={page_key:string;seo_title:string;seo_description:string;canonical_url:string;og_image:string};
const emptySeo:SeoForm={site_name:'',site_url:'',default_title:'',default_description:'',default_og_image:'',google_site_verification:'',bing_site_verification:'',google_analytics_id:''};
export default function SeoScreen(){
  const {authenticated,locked}=useAuth();const {colors}=useTheme();const query=useQuery({queryKey:['settings'],queryFn:settingsApi.get,enabled:authenticated});const [seo,setSeo]=useState<SeoForm>(emptySeo);const [pages,setPages]=useState<PageSeo[]>([]);const [message,setMessage]=useState('');const [error,setError]=useState('');const [working,setWorking]=useState(false);
  useEffect(()=>{const raw=query.data?.seo as Record<string,unknown>|undefined;if(raw)setSeo({site_name:String(raw.site_name??''),site_url:String(raw.site_url??''),default_title:String(raw.default_title??''),default_description:String(raw.default_description??''),default_og_image:String(raw.default_og_image??''),google_site_verification:String(raw.google_site_verification??''),bing_site_verification:String(raw.bing_site_verification??''),google_analytics_id:String(raw.google_analytics_id??'')});const rawPages=query.data?.pages;if(Array.isArray(rawPages))setPages(rawPages.map(raw=>{const page=raw as Record<string,unknown>;return {page_key:String(page.page_key??''),seo_title:String(page.seo_title??''),seo_description:String(page.seo_description??''),canonical_url:String(page.canonical_url??''),og_image:String(page.og_image??'')}}));},[query.data]);
  if(locked)return <Redirect href="/unlock"/>;if(!authenticated)return <Redirect href="/login"/>;if(query.isLoading)return <Screen><LoadingState/></Screen>;if(query.isError)return <Screen><ErrorState message={query.error instanceof Error?query.error.message:'Unable to load SEO settings.'} onRetry={()=>void query.refetch()}/></Screen>;
  const setGeneral=(key:keyof SeoForm,value:string)=>setSeo(current=>({...current,[key]:value}));
  const saveGeneral=async()=>{setWorking(true);setError('');setMessage('');try{await settingsApi.updateSeo(seo);setMessage('General SEO saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save SEO.');}finally{setWorking(false);}};
  const savePages=async()=>{setWorking(true);setError('');setMessage('');try{await settingsApi.updatePageSeo(pages);setMessage('Page SEO saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save page SEO.');}finally{setWorking(false);}};
  return <Screen><Title subtitle="Edit the same SEO configuration used by server-rendered public pages.">SEO</Title><Card><Text style={{color:colors.text,fontSize:17,fontWeight:'800',marginBottom:14}}>Site SEO</Text><Field label="Site name" value={seo.site_name} onChangeText={v=>setGeneral('site_name',v)}/><Field label="Canonical site URL" value={seo.site_url} onChangeText={v=>setGeneral('site_url',v)} autoCapitalize="none"/><Field label="Default title" value={seo.default_title} onChangeText={v=>setGeneral('default_title',v)}/><Field label="Default description" multiline value={seo.default_description} onChangeText={v=>setGeneral('default_description',v)}/><Field label="Default OG image" value={seo.default_og_image} onChangeText={v=>setGeneral('default_og_image',v)}/><Field label="Google verification" value={seo.google_site_verification} onChangeText={v=>setGeneral('google_site_verification',v)}/><Field label="Bing verification" value={seo.bing_site_verification} onChangeText={v=>setGeneral('bing_site_verification',v)}/><Field label="GA4 measurement ID" value={seo.google_analytics_id} onChangeText={v=>setGeneral('google_analytics_id',v)} autoCapitalize="characters"/><PrimaryButton title="Save Site SEO" loading={working} onPress={()=>void saveGeneral()}/></Card>
    <Text style={{color:colors.text,fontSize:18,fontWeight:'800',marginTop:8,marginBottom:10}}>Page SEO</Text>{pages.map((page,index)=><Card key={page.page_key}><Text style={{color:colors.text,fontSize:15,fontWeight:'800',textTransform:'capitalize',marginBottom:12}}>{page.page_key}</Text><Field label="SEO title" value={page.seo_title} onChangeText={v=>setPages(current=>current.map((item,i)=>i===index?{...item,seo_title:v}:item))}/><Field label="SEO description" multiline value={page.seo_description} onChangeText={v=>setPages(current=>current.map((item,i)=>i===index?{...item,seo_description:v}:item))}/><Field label="Canonical URL" value={page.canonical_url} onChangeText={v=>setPages(current=>current.map((item,i)=>i===index?{...item,canonical_url:v}:item))}/><Field label="OG image" value={page.og_image} onChangeText={v=>setPages(current=>current.map((item,i)=>i===index?{...item,og_image:v}:item))}/></Card>)}<PrimaryButton title="Save Page SEO" loading={working} onPress={()=>void savePages()}/>{error?<Text accessibilityRole="alert" style={{color:colors.danger,marginTop:10}}>{error}</Text>:null}{message?<Text style={{color:colors.success,marginTop:10}}>{message}</Text>:null}</Screen>;
}
