import React from 'react';
import {Text,View} from 'react-native';
import {Redirect} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {dashboardApi} from '../src/api/dashboard.api';
import {useAuth} from '../src/auth/AuthProvider';
import {Card,ErrorState,LoadingState,Screen,StatCard,Title} from '../src/components/ui';
import {useTheme} from '../src/theme/ThemeProvider';

const money=new Intl.NumberFormat('fr-MA',{style:'currency',currency:'MAD',maximumFractionDigits:0});
export default function StatisticsScreen(){const {authenticated,locked}=useAuth();const {colors}=useTheme();const query=useQuery({queryKey:['dashboard'],queryFn:dashboardApi.stats,enabled:authenticated});if(locked)return <Redirect href="/unlock"/>;if(!authenticated)return <Redirect href="/login"/>;if(query.isLoading)return <Screen><LoadingState/></Screen>;if(query.isError||!query.data)return <Screen><ErrorState message={query.error instanceof Error?query.error.message:'Unable to load statistics.'} onRetry={()=>void query.refetch()}/></Screen>;const d=query.data;const maxRevenue=Math.max(1,...d.revenue_history.map(row=>Number(row.amount)));const maxCategory=Math.max(1,...d.distribution.map(row=>row.count));return <Screen><Title subtitle="Real values calculated by the existing portfolio backend.">Statistics</Title><View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><StatCard label="Projects" value={d.projects}/><StatCard label="Completed" value={d.completed}/><StatCard label="Clients" value={d.clients}/><StatCard label="Revenue" value={money.format(d.revenue)}/></View><Text style={{color:colors.text,fontSize:18,fontWeight:'800',marginTop:18,marginBottom:10}}>Projects by category</Text><Card>{d.distribution.map(row=><View key={row.category} style={{marginBottom:13}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:colors.text,fontWeight:'600'}}>{row.category}</Text><Text style={{color:colors.textMuted}}>{row.count}</Text></View><View style={{height:8,borderRadius:99,backgroundColor:colors.input,marginTop:6,overflow:'hidden'}}><View style={{height:'100%',width:`${Math.max(5,row.count/maxCategory*100)}%`,backgroundColor:colors.primary,borderRadius:99}}/></View></View>)}</Card><Text style={{color:colors.text,fontSize:18,fontWeight:'800',marginTop:10,marginBottom:10}}>Paid revenue · last months</Text><Card>{d.revenue_history.length?d.revenue_history.map(row=><View key={row.month} style={{marginBottom:13}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:colors.text,fontWeight:'600'}}>{row.month}</Text><Text style={{color:colors.textMuted}}>{money.format(Number(row.amount))}</Text></View><View style={{height:8,borderRadius:99,backgroundColor:colors.input,marginTop:6,overflow:'hidden'}}><View style={{height:'100%',width:`${Math.max(4,Number(row.amount)/maxRevenue*100)}%`,backgroundColor:colors.success,borderRadius:99}}/></View></View>):<Text style={{color:colors.textMuted}}>No paid invoice history yet.</Text>}</Card></Screen>;}
