import type {ManagedResource} from '../../api/resources.api';

type Choice={label:string;value:string};
export type ResourceField={key:string;label:string;kind?:'text'|'multiline'|'number'|'email'|'date'|'boolean'|'choice';required?:boolean;choices?:Choice[]};
export type ResourceConfig={title:string;singular:string;fields:ResourceField[];primary:string;secondary?:string;status?:string};

export const resourceConfigs:Record<ManagedResource,ResourceConfig>={
  services:{title:'Services',singular:'Service',primary:'title',secondary:'description',fields:[{key:'title',label:'Title',required:true},{key:'description',label:'Description',kind:'multiline',required:true},{key:'icon',label:'Lucide icon',required:true},{key:'order_position',label:'Order',kind:'number',required:true},{key:'active',label:'Active',kind:'boolean'}]},
  skills:{title:'Skills',singular:'Skill',primary:'name',secondary:'category',fields:[{key:'name',label:'Name',required:true},{key:'category',label:'Category',kind:'choice',required:true,choices:['Front-end','Back-end','Outils & DevOps','Design & Autres'].map(value=>({label:value,value}))},{key:'percentage',label:'Percentage',kind:'number',required:true},{key:'icon',label:'Icon'},{key:'order_position',label:'Order',kind:'number',required:true}]},
  clients:{title:'Clients',singular:'Client',primary:'name',secondary:'email',fields:[{key:'name',label:'Name',required:true},{key:'company',label:'Company'},{key:'email',label:'Email',kind:'email',required:true},{key:'phone',label:'Phone'},{key:'notes',label:'Notes',kind:'multiline'}]},
  tasks:{title:'Tasks',singular:'Task',primary:'title',secondary:'description',status:'status',fields:[{key:'title',label:'Title',required:true},{key:'description',label:'Description',kind:'multiline'},{key:'status',label:'Status',kind:'choice',required:true,choices:[{label:'To Do',value:'todo'},{label:'In Progress',value:'in_progress'},{label:'Done',value:'done'}]},{key:'priority',label:'Priority',kind:'choice',required:true,choices:['low','medium','high'].map(value=>({label:value,value}))},{key:'due_date',label:'Due date (YYYY-MM-DD)',kind:'date'}]},
  quotes:{title:'Quotes',singular:'Quote',primary:'title',secondary:'number',status:'status',fields:[{key:'number',label:'Quote number'},{key:'client_id',label:'Client ID',kind:'number'},{key:'title',label:'Title',required:true},{key:'amount',label:'Amount (MAD)',kind:'number',required:true},{key:'status',label:'Status',kind:'choice',required:true,choices:['draft','sent','accepted','rejected'].map(value=>({label:value,value}))},{key:'due_date',label:'Due date (YYYY-MM-DD)',kind:'date'},{key:'notes',label:'Notes',kind:'multiline'}]},
  invoices:{title:'Invoices',singular:'Invoice',primary:'title',secondary:'number',status:'status',fields:[{key:'number',label:'Invoice number'},{key:'client_id',label:'Client ID',kind:'number'},{key:'title',label:'Title',required:true},{key:'amount',label:'Amount (MAD)',kind:'number',required:true},{key:'status',label:'Status',kind:'choice',required:true,choices:['draft','sent','paid','overdue'].map(value=>({label:value,value}))},{key:'due_date',label:'Due date (YYYY-MM-DD)',kind:'date'},{key:'paid_at',label:'Paid date (YYYY-MM-DD)',kind:'date'},{key:'notes',label:'Notes',kind:'multiline'}]}
};

export function isManagedResource(value:string|undefined):value is ManagedResource{return Boolean(value&&value in resourceConfigs);}
