import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import {fileURLToPath} from 'node:url';
import {sameOrigin,verifyToken} from './middleware/auth.js';
import {errorHandler} from './middleware/errorHandler.js';
import {stats} from './controllers/dashboard.controller.js';
import {pool} from './config/database.js';
import authRoutes from './routes/auth.routes.js';
import projectsRoutes from './routes/projects.routes.js';
import servicesRoutes from './routes/services.routes.js';
import skillsRoutes from './routes/skills.routes.js';
import messagesRoutes from './routes/messages.routes.js';
import clientsRoutes from './routes/clients.routes.js';
import tasksRoutes from './routes/tasks.routes.js';
import quotesRoutes from './routes/quotes.routes.js';
import invoicesRoutes from './routes/invoices.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import settingsRoutes from './routes/settings.routes.js';
import seoRoutes from './routes/seo.routes.js';
import {renderPublicPage,renderProject} from './services/seo.service.js';
export const app=express();
app.disable('x-powered-by');
if(process.env.TRUST_PROXY==='1'||process.env.VERCEL==='1')app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'","'unsafe-inline'","https://www.googletagmanager.com"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:","https://www.google-analytics.com","https://www.googletagmanager.com"],fontSrc:["'self'"],connectSrc:["'self'","https://www.google-analytics.com","https://*.google-analytics.com"],objectSrc:["'none'"],upgradeInsecureRequests:process.env.NODE_ENV==='production'?[]:null}},strictTransportSecurity:process.env.NODE_ENV==='production'?undefined:false}));
const origins=(process.env.FRONTEND_URL||'http://localhost:5000').split(',').map(s=>s.trim());
app.use((req,res,next)=>{const host=(req.get('host')||'').split(':')[0];const canonical=process.env.CANONICAL_HOST;if(process.env.NODE_ENV==='production'&&canonical&&(req.protocol!=='https'||host!==canonical))return res.redirect(301,`https://${canonical}${req.originalUrl}`);next();});
app.use(cors({origin(origin,cb){cb(null,!origin||origins.includes(origin));},credentials:true}));
app.use(morgan('tiny'));
app.use(express.json({limit:'64kb'}));app.use(express.urlencoded({extended:false,limit:'64kb'}));
app.use('/api',sameOrigin,(req,res,next)=>{res.set('Cache-Control','no-store');res.set('X-Robots-Tag','noindex, nofollow, noarchive');next();});
app.get('/api/health',async(req,res)=>{await pool.query('SELECT 1');res.json({success:true,data:{status:'ok'}});});
app.use('/api/auth',authRoutes);
app.use('/api/projects',projectsRoutes);
app.use('/api/services',servicesRoutes);
app.use('/api/skills',skillsRoutes);
app.use('/api/messages',messagesRoutes);
app.use('/api/clients',clientsRoutes);
app.use('/api/tasks',tasksRoutes);
app.use('/api/quotes',quotesRoutes);
app.use('/api/invoices',invoicesRoutes);
app.use('/api/dashboard',dashboardRoutes);
app.use('/api/settings',settingsRoutes);
app.get('/api/admin/dashboard',verifyToken,stats);
app.use('/api',(req,res)=>res.status(404).json({success:false,message:'Route introuvable.'}));
app.use(seoRoutes);
app.use('/uploads',express.static(fileURLToPath(new URL('./uploads/',import.meta.url)),{dotfiles:'deny',maxAge:'1d'}));
const cleanPages={home:'/',about:'/about',services:'/services',projects:'/projects',skills:'/skills',contact:'/contact'};
for(const [key,path] of Object.entries(cleanPages))app.get(path,async(req,res)=>res.type('html').send(await renderPublicPage(key)));
for(const [key,path] of Object.entries(cleanPages))if(key!=='home')app.get(`/${key}.html`,(req,res)=>res.redirect(301,path));
app.get('/index.html',(req,res)=>res.redirect(301,'/'));
app.get('/privacy',(req,res)=>res.set('X-Robots-Tag','noindex, follow').sendFile(fileURLToPath(new URL('../frontend/privacy.html',import.meta.url))));
app.get('/privacy.html',(req,res)=>res.redirect(301,'/privacy'));
app.get('/project.html',(req,res)=>res.redirect(301,'/projects'));
app.get('/projects/:slug',async(req,res)=>{const [rows]=await pool.execute("SELECT * FROM projects WHERE slug=? AND status='published'",[req.params.slug]);if(!rows[0])return res.status(404).sendFile(fileURLToPath(new URL('../frontend/404.html',import.meta.url)));res.type('html').send(await renderProject(rows[0]));});
app.use(express.static(fileURLToPath(new URL('../frontend/',import.meta.url)),{index:false,dotfiles:'deny',maxAge:process.env.NODE_ENV==='production'?'7d':0,setHeaders(res,file){if(file.includes('/admin/'))res.set('X-Robots-Tag','noindex, nofollow, noarchive');}}));
app.use((req,res)=>res.status(404).set('X-Robots-Tag','noindex').sendFile(fileURLToPath(new URL('../frontend/404.html',import.meta.url))));
app.use(errorHandler);
