CREATE TABLE IF NOT EXISTS mobile_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  device_id VARCHAR(128) NOT NULL,
  device_name VARCHAR(160) NOT NULL,
  platform ENUM('android','ios','unknown') NOT NULL DEFAULT 'unknown',
  refresh_token_hash CHAR(64) NOT NULL,
  biometric_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  push_token VARCHAR(512) NULL,
  notification_sound BOOLEAN NOT NULL DEFAULT TRUE,
  notification_vibration BOOLEAN NOT NULL DEFAULT TRUE,
  notification_badge BOOLEAN NOT NULL DEFAULT TRUE,
  show_sender_name BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_used_at TIMESTAMP NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  CONSTRAINT fk_mobile_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_mobile_user_device (user_id,device_id),
  UNIQUE KEY uq_mobile_refresh_hash (refresh_token_hash),
  UNIQUE KEY uq_mobile_push_token (push_token),
  KEY idx_mobile_user_active (user_id,revoked_at,expires_at),
  KEY idx_mobile_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
